### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by armond1978** [tiredofit/docker-invoiceninja#5]
Is there any plan to add support for ARM64 platforms? I'm going to run this on a Raspberry Pi.

Thank you.

**Comment by tiredofit** [comment]
My CI technically can support Arm64 builds of this, although I have no way of testing to see if it will work. I'll flip it on and see what happens.

**Comment by armond1978** [comment]
Thanks for your prompt action. Is this going to be auto published after a successful build?

**Comment by tiredofit** [comment]
If all goes well it should!

**Comment by armond1978** [comment]
I just want to confirm that the ARM64 image has been successfully published to Docker Hub. Thank you!
